@include('frontend.layout.header')
@include('frontend.register_adsl_layout.register_adsl_header')
@yield('content')
@include('frontend.register_adsl_layout.register_adsl_footer')
@include('frontend.layout.footer')
